config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  root 'tryouts#index'

  resources :guardianships
  resources :evaluations
  resources :player_tryouts
  resources :tryouts
  resources :guardians
  resources :coaches
  resources :players
  resources :users

end

app/models/tryout.rb
class Tryout < ActiveRecord::Base
  has_many :player_tryouts
end

app/controllers/tryouts_controller.rb
class TryoutsController < ApplicationController
  before_action :set_tryout , only: [:show, :edit, :update, :destroy]

  # GET /tryouts
  # GET /tryouts.json
  def index
    @tryouts = Tryout.all
  end

  # GET /tryouts/1
  # GET /tryouts/1.json
  def show
  end

  # GET /tryouts/new
  def new
    @tryout = Tryout.new
  end

  # GET /tryouts/1/edit
  def edit
  end

  # POST /tryouts
  # POST /tryouts.json
  def create
    @tryout = Tryout.new(tryout_params)

    respond_to do |format|
      if @tryout.save
        format.html { redirect_to @tryout, notice: 'Tryout was successfully created.' }
        format.json { render :show, status: :created, location: @tryout }
      else
        format.html { render :new }
        format.json { render json: @tryout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tryouts/1
  # PATCH/PUT /tryouts/1.json
  def update
    respond_to do |format|
      if @tryout.update(tryout_params)
        format.html { redirect_to @tryout, notice: 'Tryout was successfully updated.' }
        format.json { render :show, status: :ok, location: @tryout }
      else
        format.html { render :edit }
        format.json { render json: @tryout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tryouts/1
  # DELETE /tryouts/1.json
  def destroy
    @tryout.destroy
    respond_to do |format|
      format.html { redirect_to tryouts_url, notice: 'Tryout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tryout
      @tryout = Tryout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tryout_params
      params.require(:tryout).permit(:date, :fee, :address1, :address2, :city, :state, :zip)
    end
end

app/helpers/tryouts_helper.rb
module TryoutsHelper
end

app/views/tryouts/_form.html.erb
<%= form_for(@tryout) do |f| %>
  <% if @tryout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tryout.errors.count, "error") %> prohibited this tryout from being saved:</h2>

      <ul>
      <% @tryout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :fee %><br>
    <%= f.text_field :fee %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tryouts/edit.html.erb
<h1>Editing Tryout</h1>

<%= render 'form' %>

<%= link_to 'Show', @tryout %> |
<%= link_to 'Back', tryouts_path %>

app/views/tryouts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tryouts</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Fee</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tryouts.each do |tryout| %>
      <tr>
        <td><%= tryout.date %></td>
        <td><%= tryout.fee %></td>
        <td><%= tryout.address1 %></td>
        <td><%= tryout.address2 %></td>
        <td><%= tryout.city %></td>
        <td><%= tryout.state %></td>
        <td><%= tryout.zip %></td>
        <td><%= link_to 'Show', tryout %></td>
        <td><%= link_to 'Edit', edit_tryout_path(tryout) %></td>
        <td><%= link_to 'Destroy', tryout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tryout', new_tryout_path %>

app/views/tryouts/new.html.erb
<h1>New Tryout</h1>

<%= render 'form' %>

<%= link_to 'Back', tryouts_path %>

app/views/tryouts/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Date:</strong>
  <%= @tryout.date %>
</p>

<p>
  <strong>Fee:</strong>
  <%= @tryout.fee %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @tryout.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @tryout.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @tryout.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @tryout.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @tryout.zip %>
</p>

<%= link_to 'Register to this Tryout Online', new_player_path %> |
<%= link_to 'Edit', edit_tryout_path(@tryout) %> |
<%= link_to 'Back', tryouts_path %>