config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  root 'tryouts#index'

  resources :guardianships
  resources :evaluations
  resources :player_tryouts
  resources :tryouts
  resources :guardians
  resources :coaches
  resources :players
  resources :users

end

app/models/guardianship.rb
class Guardianship < ActiveRecord::Base
  belongs_to :guardian
  belongs_to :player
end

app/controllers/guardianships_controller.rb
class GuardianshipsController < ApplicationController
  before_action :set_guardianship, only: [:show, :edit, :update, :destroy]

  # GET /guardianships
  # GET /guardianships.json
  def index
    @guardianships = Guardianship.all
  end

  # GET /guardianships/1
  # GET /guardianships/1.json
  def show
  end

  # GET /guardianships/new
  def new
    @guardianship = Guardianship.new
  end

  # GET /guardianships/1/edit
  def edit
  end

  # POST /guardianships
  # POST /guardianships.json
  def create
    @guardianship = Guardianship.new(guardianship_params)

    respond_to do |format|
      if @guardianship.save
        format.html { redirect_to @guardianship, notice: 'Guardianship was successfully created.' }
        format.json { render :show, status: :created, location: @guardianship }
      else
        format.html { render :new }
        format.json { render json: @guardianship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guardianships/1
  # PATCH/PUT /guardianships/1.json
  def update
    respond_to do |format|
      if @guardianship.update(guardianship_params)
        format.html { redirect_to @guardianship, notice: 'Guardianship was successfully updated.' }
        format.json { render :show, status: :ok, location: @guardianship }
      else
        format.html { render :edit }
        format.json { render json: @guardianship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guardianships/1
  # DELETE /guardianships/1.json
  def destroy
    @guardianship.destroy
    respond_to do |format|
      format.html { redirect_to guardianships_url, notice: 'Guardianship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guardianship
      @guardianship = Guardianship.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def guardianship_params
      params.require(:guardianship).permit(:guardian_id, :player_id)
    end
end

app/helpers/guardianships_helper.rb
module GuardianshipsHelper
end

app/views/guardianships/_form.html.erb
<%= form_for(@guardianship) do |f| %>
  <% if @guardianship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@guardianship.errors.count, "error") %> prohibited this guardianship from being saved:</h2>

      <ul>
      <% @guardianship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guardian_id %><br>
    <%= f.text_field :guardian_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.text_field :player_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/guardianships/edit.html.erb
<h1>Editing Guardianship</h1>

<%= render 'form' %>

<%= link_to 'Show', @guardianship %> |
<%= link_to 'Back', guardianships_path %>

app/views/guardianships/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Guardianships</h1>

<table>
  <thead>
    <tr>
      <th>Guardian</th>
      <th>Player</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @guardianships.each do |guardianship| %>
      <tr>
        <td><%= guardianship.guardian %></td>
        <td><%= guardianship.player %></td>
        <td><%= link_to 'Show', guardianship %></td>
        <td><%= link_to 'Edit', edit_guardianship_path(guardianship) %></td>
        <td><%= link_to 'Destroy', guardianship, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Guardianship', new_guardianship_path %>

app/views/guardianships/new.html.erb
<h1>New Guardianship</h1>

<%= render 'form' %>

<%= link_to 'Back', guardianships_path %>

app/views/guardianships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Guardian:</strong>
  <%= @guardianship.guardian %>
</p>

<p>
  <strong>Player:</strong>
  <%= @guardianship.player %>
</p>

<%= link_to 'Edit', edit_guardianship_path(@guardianship) %> |
<%= link_to 'Back', guardianships_path %>