config/routes.rb
Rails.application.routes.draw do
  devise_for :profiles
  root 'tryouts#index'

  resources :guardianships
  resources :evaluations
  resources :player_tryouts
  resources :tryouts
  resources :guardians
  resources :coaches
  resources :players
  resources :users

end

app/models/player.rb
class Player < User
  has_many :player_tryouts, dependent: :destroy
  has_many :guardianships
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    authenticate_profile!
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to players_url, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:type, :first_name, :last_name, :username, :email, :phone, :gender, :dob, :address1, :address2, :city, :state, :zip, :email, :phone, :experience)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.erb
<%= form_for(@player) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% @player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.number_field :gender %>
  </div>
  <div class="field">
    <%= f.label :dob %><br>
    <%= f.datetime_select :dob %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br>
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br>
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.number_field :zip %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :experience %><br>
    <%= f.text_area :experience %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form' %>

<%= link_to 'Show', @player %> |
<%= link_to 'Back', players_path %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Players</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Gender</th>
      <th>Dob</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Experience</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= player.type %></td>
        <td><%= player.first_name %></td>
        <td><%= player.last_name %></td>
        <td><%= player.username %></td>
        <td><%= player.email %></td>
        <td><%= player.phone %></td>
        <td><%= player.gender %></td>
        <td><%= player.dob %></td>
        <td><%= player.address1 %></td>
        <td><%= player.address2 %></td>
        <td><%= player.city %></td>
        <td><%= player.state %></td>
        <td><%= player.zip %></td>
        <td><%= player.email %></td>
        <td><%= player.phone %></td>
        <td><%= player.experience %></td>
        <td><%= link_to 'Show', player %></td>
        <td><%= link_to 'Edit', edit_player_path(player) %></td>
        <td><%= link_to 'Destroy', player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_player_path %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form' %>

<%= link_to 'Back', players_path %>

app/views/players/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Type:</strong>
  <%= @player.type %>
</p>

<p>
  <strong>First name:</strong>
  <%= @player.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @player.last_name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @player.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @player.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @player.phone %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @player.gender %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @player.dob %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @player.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @player.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @player.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @player.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @player.zip %>
</p>

<p>
  <strong>Email:</strong>
  <%= @player.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @player.phone %>
</p>

<p>
  <strong>Experience:</strong>
  <%= @player.experience %>
</p>

<%= link_to 'Edit', edit_player_path(@player) %> |
<%= link_to 'Back', players_path %>